<?php

namespace Database\Seeders;

use App\Models\Customer;
use Illuminate\Database\Seeder;
use Carbon\Carbon;

class CustomerSeeder extends Seeder
{
    /**
     * Run the database seeds.
     * 
     * Adds realistic test customers with Credit, Cash, and Walking types
     * Using the exact format from your database schema
     */
    public function run(): void
    {
        $customers = [
            // Credit Customer - Full Details
            [
                'branch_id' => 2,
                'customer_id' => 'CUST-0001',
                'customer_name' => 'Ali Ahmed',
                'customer_name_ur' => 'علی احمد',
                'cnic' => '41303-9918983-9',
                'filer_type' => 'filer',
                'zone' => null,
                'contact_person' => 'Ali Ahmed',
                'mobile' => '03001234567',
                'email_address' => 'ali@example.com',
                'contact_person_2' => null,
                'mobile_2' => null,
                'email_address_2' => null,
                'customer_type' => 'credit',
                'opening_balance' => 0.00,
                'credit_limit' => 10000.00,
                'no_credit_limit' => 0,
                'address' => 'E27/286 Fakir Ka Pir',
                'status' => 'active',
            ],
            // Credit Customer - More Details
            [
                'branch_id' => 2,
                'customer_id' => 'CUST-0002',
                'customer_name' => 'Fatima Khan',
                'customer_name_ur' => 'فاطمہ خان',
                'cnic' => '42201-5678901-2',
                'filer_type' => 'filer',
                'zone' => null,
                'contact_person' => 'Fatima Khan',
                'mobile' => '03002345678',
                'email_address' => 'fatima@example.com',
                'contact_person_2' => null,
                'mobile_2' => null,
                'email_address_2' => null,
                'customer_type' => 'credit',
                'opening_balance' => 5000.00,
                'credit_limit' => 15000.00,
                'no_credit_limit' => 0,
                'address' => 'House 45, Street 23, Lahore',
                'status' => 'active',
            ],
            // Credit Customer - Wholesale
            [
                'branch_id' => 2,
                'customer_id' => 'CUST-0003',
                'customer_name' => 'Hassan Shop',
                'customer_name_ur' => 'حسن شاپ',
                'cnic' => '42602-9876543-1',
                'filer_type' => 'filer',
                'zone' => null,
                'contact_person' => 'Hassan Malik',
                'mobile' => '03003456789',
                'email_address' => 'hassan@shop.com',
                'contact_person_2' => 'Malik Hassan',
                'mobile_2' => '03001234567',
                'email_address_2' => null,
                'customer_type' => 'credit',
                'opening_balance' => 0.00,
                'credit_limit' => 50000.00,
                'no_credit_limit' => 0,
                'address' => 'Main Bazaar, Rawalpindi',
                'status' => 'active',
            ],
            // Credit Customer - Sample from your data (CUST-0004)
            [
                'branch_id' => 1,
                'customer_id' => 'CUST-0004',
                'customer_name' => 'minhaj',
                'customer_name_ur' => null,
                'cnic' => '41303-9918983-9',
                'filer_type' => 'filer',
                'zone' => null,
                'contact_person' => null,
                'mobile' => '316324656',
                'email_address' => null,
                'contact_person_2' => null,
                'mobile_2' => null,
                'email_address_2' => null,
                'customer_type' => 'credit',
                'opening_balance' => 0.00,
                'credit_limit' => 5000.00,
                'no_credit_limit' => 0,
                'address' => 'E27/286 Fakir Ka Pir',
                'status' => 'active',
            ],
            // Cash Customer - Sample from your data (CUST-0005)
            [
                'branch_id' => 3,
                'customer_id' => 'CUST-0005',
                'customer_name' => 'avesh',
                'customer_name_ur' => null,
                'cnic' => '41303-9918983-9',
                'filer_type' => 'filer',
                'zone' => null,
                'contact_person' => null,
                'mobile' => '03003647318',
                'email_address' => null,
                'contact_person_2' => null,
                'mobile_2' => null,
                'email_address_2' => null,
                'customer_type' => 'cash',
                'opening_balance' => 0.00,
                'credit_limit' => 0.00,
                'no_credit_limit' => 0,
                'address' => 'Hno 2/11B near bight future high school husri dist',
                'status' => 'active',
            ],
            // Cash Customer - General
            [
                'branch_id' => 2,
                'customer_id' => 'CUST-0006',
                'customer_name' => 'Muhammad Asif',
                'customer_name_ur' => 'محمد عاصف',
                'cnic' => '41500-1234567-8',
                'filer_type' => 'filer',
                'zone' => null,
                'contact_person' => 'Muhammad Asif',
                'mobile' => '03004567890',
                'email_address' => 'asif@example.com',
                'contact_person_2' => null,
                'mobile_2' => null,
                'email_address_2' => null,
                'customer_type' => 'cash',
                'opening_balance' => 0.00,
                'credit_limit' => 0.00,
                'no_credit_limit' => 0,
                'address' => 'Street 5, Defence, Karachi',
                'status' => 'active',
            ],
            // Credit Customer - Traders
            [
                'branch_id' => 1,
                'customer_id' => 'CUST-0007',
                'customer_name' => 'Zainab Traders',
                'customer_name_ur' => 'زینب ٹریڈرز',
                'cnic' => '42800-2345678-9',
                'filer_type' => 'filer',
                'zone' => null,
                'contact_person' => 'Zainab',
                'mobile' => '03005678901',
                'email_address' => 'zainab@traders.com',
                'contact_person_2' => null,
                'mobile_2' => null,
                'email_address_2' => null,
                'customer_type' => 'credit',
                'opening_balance' => 2000.00,
                'credit_limit' => 25000.00,
                'no_credit_limit' => 0,
                'address' => 'Saddar Bazaar, Peshawar',
                'status' => 'active',
            ],
            // Credit Customer - Multiple Contacts
            [
                'branch_id' => 3,
                'customer_id' => 'CUST-0008',
                'customer_name' => 'Ahmed Store',
                'customer_name_ur' => 'احمد سٹور',
                'cnic' => '41800-3456789-0',
                'filer_type' => 'filer',
                'zone' => null,
                'contact_person' => 'Ahmed',
                'mobile' => '03006789012',
                'email_address' => 'ahmed@store.com',
                'contact_person_2' => 'Usman',
                'mobile_2' => '03007890123',
                'email_address_2' => null,
                'customer_type' => 'credit',
                'opening_balance' => 1000.00,
                'credit_limit' => 20000.00,
                'no_credit_limit' => 0,
                'address' => 'Gulshan-e-Iqbal, Lahore',
                'status' => 'active',
            ],
            // Walking Customer - No credit limit, minimal details
            [
                'branch_id' => 3,
                'customer_id' => 'CUST-0009',
                'customer_name' => 'Walk-in Customer 1',
                'customer_name_ur' => null,
                'cnic' => null,
                'filer_type' => 'walking',
                'zone' => null,
                'contact_person' => null,
                'mobile' => null,
                'email_address' => null,
                'contact_person_2' => null,
                'mobile_2' => null,
                'email_address_2' => null,
                'customer_type' => 'walking',
                'opening_balance' => 0.00,
                'credit_limit' => 0.00,
                'no_credit_limit' => 1,
                'address' => null,
                'status' => 'active',
            ],
            // Credit Customer - mehboob (from your data as CUST-0010)
            [
                'branch_id' => 1,
                'customer_id' => 'CUST-0010',
                'customer_name' => 'mehboob',
                'customer_name_ur' => null,
                'cnic' => '41303-9918983-9',
                'filer_type' => 'filer',
                'zone' => null,
                'contact_person' => null,
                'mobile' => '316324656',
                'email_address' => null,
                'contact_person_2' => null,
                'mobile_2' => null,
                'email_address_2' => null,
                'customer_type' => 'credit',
                'opening_balance' => 0.00,
                'credit_limit' => 5000.00,
                'no_credit_limit' => 0,
                'address' => 'E27/286 Fakir Ka Pir',
                'status' => 'active',
            ],
            // Cash Customer - Market
            [
                'branch_id' => 2,
                'customer_id' => 'CUST-0011',
                'customer_name' => 'Market Point',
                'customer_name_ur' => 'مارکیٹ پوائنٹ',
                'cnic' => '42000-4567890-1',
                'filer_type' => 'filer',
                'zone' => null,
                'contact_person' => 'Manager',
                'mobile' => '03008901234',
                'email_address' => null,
                'contact_person_2' => null,
                'mobile_2' => null,
                'email_address_2' => null,
                'customer_type' => 'cash',
                'opening_balance' => 0.00,
                'credit_limit' => 0.00,
                'no_credit_limit' => 0,
                'address' => 'Islamabad Market',
                'status' => 'active',
            ],
            // Credit Customer - High Limit
            [
                'branch_id' => 1,
                'customer_id' => 'CUST-0012',
                'customer_name' => 'Premium Business',
                'customer_name_ur' => 'پریمیم بزنس',
                'cnic' => '41702-5678901-2',
                'filer_type' => 'filer',
                'zone' => null,
                'contact_person' => 'Director',
                'mobile' => '03009012345',
                'email_address' => 'premium@business.com',
                'contact_person_2' => 'Manager',
                'mobile_2' => '03001234567',
                'email_address_2' => null,
                'customer_type' => 'credit',
                'opening_balance' => 5000.00,
                'credit_limit' => 100000.00,
                'no_credit_limit' => 0,
                'address' => 'Business Park, Islamabad',
                'status' => 'active',
            ],
        ];

        // Insert or update customers
        foreach ($customers as $customer) {
            Customer::updateOrCreate(
                ['customer_id' => $customer['customer_id']],
                $customer
            );
        }

        $this->command->info('✅ ' . count($customers) . ' customers seeded successfully!');
        $this->command->info('✓ Credit customers: 8');
        $this->command->info('✓ Cash customers: 3');
        $this->command->info('✓ Walking customers: 1');
    }
}
